version: '3'
services:
    flora-api:
        env_file:
            - ".env"
        build: .
        image: flora-api
        command: flora-api
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - flora-api
